name: Docker Image CI

on:
  # push:
  #   branches: [ master ]
  schedule:
    - cron: '0 6 * * Sun'
  workflow_dispatch:

jobs:
  build:
    runs-on: alpine-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker build --build-arg PASSWORD=toor \
          --file Dockerfile \
          --tag containerpi/alpine-sshd:latest .
        echo "$DOCKER_PASSWORD" |docker login -u="$DOCKER_USER" --password-stdin
        docker push containerpi/alpine-sshd:latest
